"""
Django settings for sever_main project.

Generated by 'django-admin startproject' using Django 3.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from datetime import timedelta
from pathlib import Path

from django.conf.global_settings import STATICFILES_DIRS
from django.core.management.commands.runserver import Command as runserver

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent


def load_local_env():
    env_path = PROJECT_ROOT / ".env.local"
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_local_env()

FILES_ROOT = os.path.join(BASE_DIR, 'files')
FILES_REVIEW = os.path.join(FILES_ROOT, 'review')
FILES_APPROVED = os.path.join(FILES_ROOT, 'approved')
DATA_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 1024 * 1024 * 1024
# AUTH_USER_MODEL = 'api_auth.MyCustomUser'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("QHZHC_SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("QHZHC_SECRET_KEY is required")


def require_env(name):
    value = os.getenv(name)
    if not value:
        raise RuntimeError(f"{name} is required")
    return value


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "false").lower() == "true"


def read_csv_setting(name, default):
    value = os.getenv(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


ALLOWED_HOSTS = read_csv_setting(
    "QHZHC_ALLOWED_HOSTS",
    "localhost,127.0.0.1,[::1]",
)
runserver.default_addr = os.getenv("QHZHC_BACKEND_HOST") or "0.0.0.0"
runserver.default_port = os.getenv("QHZHC_BACKEND_PORT") or '18080'
QHZHC_ACCESS_COOKIE_NAME = os.getenv(
    "QHZHC_ACCESS_COOKIE_NAME",
    "qhzhc_access",
)
QHZHC_ACCESS_COOKIE_MAX_AGE = 48 * 60 * 60
QHZHC_ACCESS_COOKIE_SECURE = not DEBUG
QHZHC_ACCESS_COOKIE_SAMESITE = "Lax"
QHZHC_SMTP_HOST = os.getenv("QHZHC_SMTP_HOST")
QHZHC_SMTP_PORT = (
    int(os.getenv("QHZHC_SMTP_PORT")) if os.getenv("QHZHC_SMTP_PORT") else None
)
QHZHC_SMTP_USER = os.getenv("QHZHC_SMTP_USER")
QHZHC_SMTP_PASSWORD = os.getenv("QHZHC_SMTP_PASSWORD")
# Application definition

INSTALLED_APPS = [
    'daphne',
    'api_auth',
    'api_files',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api_chart',
    # 'api_chart.ChatConfig',
    'channels',
    'rest_framework',
    'rest_framework_simplejwt',
]

AUTH_USER_MODEL = 'api_auth.CustomUser'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'api_auth.middleware.CustomTokenAuthentication',  # 使用你的自定义认证类
    ),
}

##### cors资源跨域共享配置
CORS_ALLOW_CREDENTIALS = True  # 允许携带Cookie
CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOWED_ORIGINS = read_csv_setting(
    "QHZHC_FRONTEND_ORIGINS",
    "http://127.0.0.1:9527,http://localhost:9527",
)
# django-cors-headers 3.x keeps this setting name for compatibility.
CORS_ORIGIN_WHITELIST = CORS_ALLOWED_ORIGINS
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
CORS_ALLOW_METHODS = (
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
    'VIEW',
)

CORS_ALLOW_HEADERS = (
    'XMLHttpRequest',
    'X_FILENAME',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'Pragma',
    'token'  # 请求头允许自定义的字符串
)

ASGI_APPLICATION = 'sever_main.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}
###

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=48),  # 设置访问令牌的有效期
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',### 用于post请求异域
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
]

ROOT_URLCONF = 'sever_main.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(os.path.dirname(__file__), 'api_files/templates'),
                 ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sever_main.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': os.getenv("QHZHC_DB_NAME") or 'postgres',
        'USER': os.getenv("QHZHC_DB_USER") or 'postgres',
        "PASSWORD": require_env("QHZHC_DB_PASSWORD"),
        "HOST": os.getenv("QHZHC_DB_HOST") or 'localhost',
        'PORT': int(os.getenv("QHZHC_DB_PORT") or 5432),
        'OPTIONS': {
            'options': '-c timezone=Asia/Shanghai'
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]





# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# STATICFILES_DIRS =[
#          os.path.join(BASE DIR,'static'),
#           BASE_DIR,
# ]
# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')
