# Generated by Django 4.2.27 on 2026-03-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AppDatares",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="主键id"
                    ),
                ),
                ("titlename", models.CharField(max_length=255, verbose_name="标题名称")),
                ("filepath", models.CharField(max_length=255, verbose_name="文件目录")),
                ("ip_port", models.CharField(max_length=255, verbose_name="替换的ip地址")),
                ("filetype", models.CharField(max_length=255, verbose_name="文件类型")),
                ("describtion", models.CharField(max_length=255, verbose_name="描述")),
                ("author", models.CharField(max_length=255, verbose_name="作者")),
                ("filetime", models.CharField(max_length=255, verbose_name="文件时间")),
                ("fileurl", models.CharField(max_length=255, verbose_name="文件链接")),
                ("htmlpath", models.CharField(max_length=255, verbose_name="html链接")),
                ("pngpath", models.CharField(max_length=255, verbose_name="图片路径")),
                ("is_exterlinks", models.BooleanField(verbose_name="判断是否为外部链接")),
            ],
            options={
                "db_table": "api_datares",
            },
        ),
        migrations.CreateModel(
            name="Appexpert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="主键id"
                    ),
                ),
                ("maininfo", models.CharField(max_length=2000, verbose_name="主要信息")),
                ("homepage", models.CharField(max_length=2000, verbose_name="主页")),
                ("address", models.CharField(max_length=255, verbose_name="通讯邮箱地址")),
                ("imageurl", models.CharField(max_length=255, verbose_name="图片")),
                ("datatype", models.CharField(max_length=255, verbose_name="类型")),
                ("insertime", models.DateField(verbose_name="日期时间")),
                ("expertname", models.CharField(max_length=255, verbose_name="专家名称")),
                ("direction", models.CharField(max_length=255, verbose_name="研究方向")),
            ],
            options={
                "db_table": "expertmation",
            },
        ),
        migrations.CreateModel(
            name="File_information",
            fields=[
                ("filename", models.CharField(max_length=255, verbose_name="文件名称")),
                ("filedir", models.CharField(max_length=255, verbose_name="dir")),
                ("uploadtime", models.CharField(max_length=255, verbose_name="最近下载时间")),
                ("filetype", models.CharField(max_length=255, verbose_name="文件类型")),
                (
                    "is_examine",
                    models.BooleanField(max_length=255, verbose_name="文件是否经过审核"),
                ),
                (
                    "downloadtime",
                    models.CharField(max_length=255, verbose_name="文件最近下载时间"),
                ),
                (
                    "fileid",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="唯一主键id"
                    ),
                ),
                (
                    "approvedstrtime",
                    models.CharField(max_length=255, verbose_name="文件审核时间"),
                ),
                (
                    "username",
                    models.CharField(
                        default="default_username", max_length=255, verbose_name="上传作者"
                    ),
                ),
                (
                    "datasource",
                    models.CharField(
                        default="default_source", max_length=255, verbose_name="数据资源"
                    ),
                ),
                (
                    "filedescrib",
                    models.CharField(
                        default="default_filedescrib",
                        max_length=255,
                        verbose_name="文件审核时间",
                    ),
                ),
                (
                    "uniqueid",
                    models.CharField(
                        default="default_filedescrib",
                        max_length=255,
                        verbose_name="以unique sequence指定的uuid",
                    ),
                ),
            ],
            options={
                "db_table": "file_information",
            },
        ),
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        primary_key=True, serialize=False, verbose_name="主键id"
                    ),
                ),
                ("filedescire", models.CharField(max_length=255, verbose_name="文件描述")),
                ("ip_port", models.CharField(max_length=255, verbose_name="替换的ip地址")),
                ("pngpath", models.CharField(max_length=255, verbose_name="图片路径")),
                ("serial_number", models.IntegerField(verbose_name="图片序号")),
                ("filetime", models.CharField(max_length=255, verbose_name="文件时间")),
                ("fileurl", models.CharField(max_length=255, verbose_name="文件链接")),
                ("is_home_page", models.BooleanField(verbose_name="是否为主页图片")),
            ],
            options={
                "db_table": "api_home_page",
            },
        ),
        migrations.CreateModel(
            name="HomepageImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "api_homepage_image",
            },
        ),
    ]
