# Generated by Django 3.2.18 on 2024-08-02 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0001_initial'),
    ]

    operations = []
