# Generated by Django 3.2.18 on 2024-08-06 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_auto_20240802_1004'),
    ]

    operations = []
