# Generated by Django 4.2.27 on 2026-03-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_auth", "0003_auto_20240806_1352"),
    ]

    operations = [
        migrations.CreateModel(
            name="Verification",
            fields=[
                ("first_name", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "email",
                    models.CharField(
                        max_length=255, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("verification_code", models.IntegerField(blank=True, null=True)),
                ("sendnumber", models.IntegerField(blank=True, null=True)),
                ("judge_time", models.CharField(blank=True, max_length=255, null=-1)),
            ],
            options={
                "db_table": "verification_sys",
            },
        ),
    ]
